version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17
    working_directory: ~/repo

jobs:
  sonar_scan:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: npm install -g sonar-scanner
      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.host.url=$SONAR_HOST_URL

workflows:
  version: 2
  scan-workflow:
    jobs:
      - sonar_scan
