CREATE DATABASE SecurePortal;
GO


CREATE TABLE Users (
  id INT IDENTITY(1,1) PRIMARY KEY,
  username NVARCHAR(100) NOT NULL UNIQUE,
  password NVARCHAR(255) NOT NULL,
  idNumber NVARCHAR(50) NOT NULL UNIQUE,
  accountNumber NVARCHAR(50) NOT NULL UNIQUE,
  createdAt DATETIME DEFAULT GETDATE(),
  updatedAt DATETIME DEFAULT GETDATE()
);
